export const colorVariants = {
    green: {
        hoverShadow: "hover:shadow-green-500/30",
        backgroundShade: "bg-green-500/30",
        hoverFocusRing: "focus:ring-green-400",
        foreground: "text-green-500",
        background: "bg-green-500",
        hoverForeground: "hover:text-green-500",
        hoverBackground: "hover:bg-green-600",
    },
    red: {
        hoverFocusRing: "focus:ring-red-400",
        backgroundShade: "bg-red-500/30",
        hoverShadow: "hover:shadow-red-500/30",
        foreground: "text-red-500",
        background: "bg-red-500",
        hoverForeground: "hover:text-red-500",
        hoverBackground: "hover:bg-red-600",
    },
    amber: {
        hoverFocusRing: "focus:ring-amber-400",
        backgroundShade: "bg-amber-500/30",
        hoverShadow: "hover:shadow-amber-500/30",
        foreground: "text-amber-500",
        background: "bg-amber-500",
        hoverForeground: "hover:text-amber-500",
        hoverBackground: "hover:bg-amber-600",
    },
    cyan: {
        hoverFocusRing: "focus:ring-cyan-400",
        backgroundShade: "bg-cyan-500/30",
        hoverShadow: "hover:shadow-cyan-500/30",
        foreground: "text-cyan-500",
        background: "bg-cyan-500",
        hoverForeground: "hover:text-cyan-500",
        hoverBackground: "hover:bg-cyan-600",
    },
    violet: {
        hoverFocusRing: "focus:ring-violet-400",
        backgroundShade: "bg-violet-500/30",
        hoverShadow: "hover:shadow-violet-500/30",
        foreground: "text-violet-500",
        background: "bg-violet-500",
        hoverForeground: "hover:text-violet-500",
        hoverBackground: "hover:bg-violet-600",
    },
    pink: {
        hoverFocusRing: "focus:ring-pink-400",
        backgroundShade: "bg-pink-500/30",
        hoverShadow: "hover:shadow-pink-500/30",
        foreground: "text-pink-500",
        background: "bg-pink-500",
        hoverForeground: "hover:text-pink-500",
        hoverBackground: "hover:bg-pink-600",
    },
};
