/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/health/is-authorised": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHelloAuthorized"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/health/is-super-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHelloSuperAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_findOne"];
        put?: never;
        post?: never;
        /** @description Limited to Super Admin role or the user themselves. */
        delete: operations["UserController_remove"];
        options?: never;
        head?: never;
        /** @description Limited to Super Admin role or the user themselves. */
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users in the system. Limited to Super Admin role. */
        get: operations["UserController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email-client/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmailClientController_verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email-client/peekalljobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmailClientController_peekQueueJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email-client/peekfailedjobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmailClientController_peekFailedQueueJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganisationController_findOne"];
        put?: never;
        post?: never;
        delete: operations["OrganisationController_remove"];
        options?: never;
        head?: never;
        patch: operations["OrganisationController_update"];
        trace?: never;
    };
    "/organisation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganisationController_findAllForUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation/{orgUuid}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganisationMembershipsController_findAll"];
        put?: never;
        post: operations["OrganisationMembershipsController_createOrUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation/{orgUuid}/memberships/{membershipUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OrganisationMembershipsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/github-user/{orgUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserOnboardingController_getAllForOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/github-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserOnboardingController_addForOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/stripe/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StripeCheckoutController_createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/stripe/customer-portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StripeCustomerPortalController_createCustomerPortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/stripe/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StripeEventsController_getLastEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/stripe/webhook-receiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StripeWebhookController_webhookReceiver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/stripe/peekalljobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StripeWebhookController_peekQueueJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/stripe/peekfailedjobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StripeWebhookController_peekFailedQueueJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AllSubscriptionsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation/{orgUuid}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganisationSubscriptionsController_findAll"];
        put?: never;
        post: operations["OrganisationSubscriptionsController_addSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation/{orgUuid}/subscriptions/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OrganisationSubscriptionsController_deleteSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentSessionReferenceController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-files/{productKey}/{projectKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CourseFilesController_listProjectFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-files/{productKey}/{projectKey}/contents/{b64Path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CourseFilesController_getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-files/{productKey}/{projectKey}/contents-markdown/{markdownB64Path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CourseFilesController_getMarkdownFileAsHtml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-files/{productKey}/open/{projectKey}/contents/{b64Path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OpenCourseFilesController_getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-files/{productKey}/open/{projectKey}/contents-markdown/{markdownB64Path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OpenCourseFilesController_getMarkdownFileAsHtml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-files/{productKey}/open/{projectKey}/nearest-readme/{b64Path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OpenCourseFilesController_getNearestHtmlReadmeForFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-meta/{productKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CourseMetaController_listAllProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-powers/reset-database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SuperPowersController_resetDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitationController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitationController_getAllForOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitationController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["InvitationController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubscriptionAssetsController_getAssetsForOrg"];
        put?: never;
        post: operations["SubscriptionAssetsController_addAssetRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription-assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SubscriptionAssetsController_deleteAssetRecord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            result: string;
        };
        MembershipRole: {
            id: number;
            membershipId: number;
            name: string;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
        };
        OrganisationMembership: {
            id: number;
            uuid: string;
            userId: number;
            organisation: Record<string, never>;
            organisationId: number;
            roles?: components["schemas"]["MembershipRole"][];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            deletedDate?: string;
            /** Format: date-time */
            updateDate: string;
        };
        UserDto: {
            /** @description Is the user a super user. Only set if the user is the current user. Will not be set for list responses. */
            isSuper?: boolean;
            id: number;
            email: string;
            uuid: string;
            emailVerified: boolean;
            blocked: boolean;
            name?: string;
            familyName?: string;
            givenName?: string;
            picture?: string;
            auth0UserId?: string;
            username?: string;
            memberships: components["schemas"]["OrganisationMembership"][];
            activeSubscriptionProductKeys: string[];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
            /** Format: date-time */
            deletedDate?: string;
        };
        UserApiKey: {
            id: number;
            uuid: string;
            apiKey: string;
            description: string;
            userId: number;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
        };
        User: {
            id: number;
            email: string;
            uuid: string;
            emailVerified: boolean;
            blocked: boolean;
            name?: string;
            familyName?: string;
            givenName?: string;
            picture?: string;
            auth0UserId?: string;
            username?: string;
            memberships?: components["schemas"]["OrganisationMembership"][];
            apiKeys?: components["schemas"]["UserApiKey"][];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
            /** Format: date-time */
            deletedDate?: string;
        };
        UpdateUserDto: Record<string, never>;
        BooleanResult: {
            result: boolean;
        };
        QueueItemDto: {
            id: string;
            /** Format: date-time */
            queueDateLocal: string;
            result: string;
            data: string;
            failReason?: string;
        };
        OrganisationSubscriptionRecord: {
            id: number;
            uuid: string;
            internalSku: string;
            productDisplayName: string;
            paymentSystemTransactionId: string;
            paymentSystemProductId: string;
            paymentSystemCustomerId: string;
            paymentSystemCustomerEmail: string;
            paymentSystemMode: string;
            paymentSystemName: string;
            /** Format: date-time */
            validUntil: string;
            organisationId: number;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
            /** Format: date-time */
            deletedDate?: string;
        };
        Organisation: {
            id: number;
            uuid: string;
            subscriptionRecords?: components["schemas"]["OrganisationSubscriptionRecord"][];
            name: string;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
            /** Format: date-time */
            deletedDate?: string;
        };
        UpdateOrganisationDto: {
            members?: components["schemas"]["User"][];
            owner?: components["schemas"]["User"];
            name?: string;
        };
        CreateUpdateMembershipDto: {
            userId: number;
            roles: string[];
        };
        OrgGithubUser: {
            id: number;
            orgUuid: string;
            ghUsername: string;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
        };
        OrgGithubUserDto: {
            ghUsername: string;
            orgUuid: string;
        };
        StripeCheckoutLineItem: {
            price: string;
            quantity: number;
        };
        StripeCheckoutSessionRequestDto: {
            organisationUuid?: string;
            lineItems: components["schemas"]["StripeCheckoutLineItem"][];
            mode: string;
            /** @description The path on frontend to which Stripe should redirect the customer after payment. This is appended to the host configured in the StripeClientConfigurationService */
            successFrontendPath: string;
            /** @description The path on frontend to which Stripe should redirect the customer after payment cancellation. This is appended to the host configured in the StripeClientConfigurationService */
            cancelFrontendPath?: string;
        };
        StripeCheckoutSessionResponseDto: {
            stripeSessionId: string;
            stripeSessionUrl: string;
        };
        StripeCustomerPortalRequestDto: {
            subscriptionRecordUuid: string;
            returnUrl: string;
        };
        StripeCustomerPortalResponseDto: {
            sessionUrl: string;
        };
        StripeCheckoutEvent: {
            id: number;
            /** Format: date-time */
            createdDate: string;
            clientReferenceId?: string;
            stripeSessionId: string;
            stripeObjectType: string;
            stripeDataAsString: string;
        };
        SaveOrganisationSubscriptionRecordDto: {
            productDisplayName: string;
            paymentSystemTransactionId: string;
            paymentSystemProductId: string;
            millerPaymentReferenceUuid?: string;
            paymentSystemCustomerId: string;
            paymentSystemCustomerEmail: string;
            paymentSystemMode: string;
            paymentSystemName: string;
            internalSku: string;
            /** Format: date-time */
            validUntil: string;
        };
        PaymentSessionReference: {
            id: number;
            uuid: string;
            /** Format: date-time */
            createdDate: string;
        };
        FileStructureDto: {
            name: string;
            /** @enum {string} */
            type: "folder" | "file";
            isOpen?: boolean;
            fileLocation: string;
            children?: components["schemas"]["FileStructureDto"][];
        };
        FileMetaDto: {
            contents: string;
            fileLocation: string;
            fileName: string;
            nearestReadmeLocation?: string;
        };
        CourseMetaDto: {
            key: string;
            rootNodeName: string;
            demoPaths: string[];
            rootLocation: string;
            demoFileLinkHref: string;
            demoFileLinkText: string;
            name: string;
            color: string;
            isOpenSource: boolean;
        };
        Invitation: {
            id: number;
            uuid: string;
            givenName: string;
            emailAddress: string;
            /** Format: date-time */
            notificationSent?: string;
            /** Format: date-time */
            expiresOn: string;
            /** Format: date-time */
            acceptedOn?: string;
            organisationMembership: components["schemas"]["OrganisationMembership"];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
            /** Format: date-time */
            deletedDate?: string;
        };
        CreateInvitationDto: {
            givenName: string;
            emailAddress: string;
            organisationId: number;
        };
        SubscriptionAsset: {
            id: number;
            internalSku: string;
            uri: string;
            description: string;
            displayName: string;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updateDate: string;
        };
        SaveSubscriptionAssetDto: {
            id?: number;
            internalSku: string;
            uri: string;
            description: string;
            displayName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    AppController_getHelloAuthorized: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    AppController_getHelloSuperAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    UserController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    UserController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResult"];
                };
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResult"];
                };
            };
        };
    };
    UserController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    EmailClientController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResult"];
                };
            };
        };
    };
    EmailClientController_peekQueueJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemDto"][];
                };
            };
        };
    };
    EmailClientController_peekFailedQueueJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemDto"][];
                };
            };
        };
    };
    OrganisationController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisation"];
                };
            };
        };
    };
    OrganisationController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResult"];
                };
            };
        };
    };
    OrganisationController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganisationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisation"];
                };
            };
        };
    };
    OrganisationController_findAllForUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisation"][];
                };
            };
        };
    };
    OrganisationMembershipsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationMembership"][];
                };
            };
        };
    };
    OrganisationMembershipsController_createOrUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpdateMembershipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisation"];
                };
            };
        };
    };
    OrganisationMembershipsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgUuid: string;
                membershipUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResult"];
                };
            };
        };
    };
    UserOnboardingController_getAllForOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgGithubUser"][];
                };
            };
        };
    };
    UserOnboardingController_addForOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgGithubUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgGithubUser"];
                };
            };
        };
    };
    StripeCheckoutController_createCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StripeCheckoutSessionRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeCheckoutSessionResponseDto"];
                };
            };
        };
    };
    StripeCustomerPortalController_createCustomerPortalSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StripeCustomerPortalRequestDto"];
            };
        };
        responses: {
            /** @description The URL to the customer portal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeCustomerPortalResponseDto"];
                };
            };
        };
    };
    StripeEventsController_getLastEvents: {
        parameters: {
            query: {
                skip: number;
                take: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeCheckoutEvent"][];
                };
            };
        };
    };
    StripeWebhookController_webhookReceiver: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeWebhookController_peekQueueJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemDto"][];
                };
            };
        };
    };
    StripeWebhookController_peekFailedQueueJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemDto"][];
                };
            };
        };
    };
    AllSubscriptionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSubscriptionRecord"][];
                };
            };
        };
    };
    OrganisationSubscriptionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSubscriptionRecord"][];
                };
            };
        };
    };
    OrganisationSubscriptionsController_addSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveOrganisationSubscriptionRecordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSubscriptionRecord"][];
                };
            };
        };
    };
    OrganisationSubscriptionsController_deleteSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgUuid: string;
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResult"];
                };
            };
        };
    };
    PaymentSessionReferenceController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSessionReference"][];
                };
            };
        };
    };
    CourseFilesController_listProjectFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectKey: string;
                productKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileStructureDto"];
                };
            };
        };
    };
    CourseFilesController_getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectKey: string;
                productKey: string;
                b64Path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetaDto"];
                };
            };
        };
    };
    CourseFilesController_getMarkdownFileAsHtml: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectKey: string;
                productKey: string;
                markdownB64Path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetaDto"];
                };
            };
        };
    };
    OpenCourseFilesController_getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectKey: string;
                b64Path: string;
                productKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetaDto"];
                };
            };
        };
    };
    OpenCourseFilesController_getMarkdownFileAsHtml: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectKey: string;
                markdownB64Path: string;
                productKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetaDto"];
                };
            };
        };
    };
    OpenCourseFilesController_getNearestHtmlReadmeForFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectKey: string;
                b64Path: string;
                productKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetaDto"];
                };
            };
        };
    };
    CourseMetaController_listAllProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseMetaDto"][];
                };
            };
        };
    };
    SuperPowersController_resetDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationController_accept: {
        parameters: {
            query: {
                invitationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationController_getAllForOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"][];
                };
            };
        };
    };
    InvitationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    InvitationController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    SubscriptionAssetsController_getAssetsForOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionAsset"][];
                };
            };
        };
    };
    SubscriptionAssetsController_addAssetRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSubscriptionAssetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionAsset"][];
                };
            };
        };
    };
    SubscriptionAssetsController_deleteAssetRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
