/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InlineResponse200,
    InlineResponse200FromJSON,
    InlineResponse200ToJSON,
    InlineResponse503,
    InlineResponse503FromJSON,
    InlineResponse503ToJSON,
} from '../models';

/**
 * ApplicationSupportApi - interface
 * 
 * @export
 * @interface ApplicationSupportApiInterface
 */
export interface ApplicationSupportApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationSupportApiInterface
     */
    appControllerGetHelloRaw(): Promise<runtime.ApiResponse<string>>;

    /**
     */
    appControllerGetHello(): Promise<string>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationSupportApiInterface
     */
    appControllerGetHelloAuthorizedRaw(): Promise<runtime.ApiResponse<string>>;

    /**
     */
    appControllerGetHelloAuthorized(): Promise<string>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationSupportApiInterface
     */
    healthControllerCheckRaw(): Promise<runtime.ApiResponse<InlineResponse200>>;

    /**
     */
    healthControllerCheck(): Promise<InlineResponse200>;

}

/**
 * 
 */
export class ApplicationSupportApi extends runtime.BaseAPI implements ApplicationSupportApiInterface {

    /**
     */
    async appControllerGetHelloRaw(): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async appControllerGetHello(): Promise<string> {
        const response = await this.appControllerGetHelloRaw();
        return await response.value();
    }

    /**
     */
    async appControllerGetHelloAuthorizedRaw(): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/is-authorised`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async appControllerGetHelloAuthorized(): Promise<string> {
        const response = await this.appControllerGetHelloAuthorizedRaw();
        return await response.value();
    }

    /**
     */
    async healthControllerCheckRaw(): Promise<runtime.ApiResponse<InlineResponse200>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse200FromJSON(jsonValue));
    }

    /**
     */
    async healthControllerCheck(): Promise<InlineResponse200> {
        const response = await this.healthControllerCheckRaw();
        return await response.value();
    }

}
