/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateUpdateMembershipDto,
    CreateUpdateMembershipDtoFromJSON,
    CreateUpdateMembershipDtoToJSON,
    Organisation,
    OrganisationFromJSON,
    OrganisationToJSON,
    OrganisationSubscriptionRecord,
    OrganisationSubscriptionRecordFromJSON,
    OrganisationSubscriptionRecordToJSON,
    SaveOrganisationSubscriptionRecordDto,
    SaveOrganisationSubscriptionRecordDtoFromJSON,
    SaveOrganisationSubscriptionRecordDtoToJSON,
    UpdateOrganisationDto,
    UpdateOrganisationDtoFromJSON,
    UpdateOrganisationDtoToJSON,
} from '../models';

export interface OrganisationControllerFindOneRequest {
    uuid: string;
}

export interface OrganisationControllerRemoveRequest {
    uuid: string;
}

export interface OrganisationControllerUpdateRequest {
    uuid: string;
    updateOrganisationDto: UpdateOrganisationDto;
}

export interface OrganisationMembershipsControllerCreateOrUpdateRequest {
    orgUuid: string;
    createUpdateMembershipDto: CreateUpdateMembershipDto;
}

export interface OrganisationMembershipsControllerFindAllRequest {
    orgUuid: string;
}

export interface OrganisationMembershipsControllerRemoveRequest {
    orgUuid: string;
    membershipUuid: string;
}

export interface OrganisationSubscriptionsControllerAddSubscriptionRequest {
    orgUuid: string;
    saveOrganisationSubscriptionRecordDto: SaveOrganisationSubscriptionRecordDto;
}

export interface OrganisationSubscriptionsControllerDeleteSubscriptionRequest {
    orgUuid: string;
    uuid: string;
}

export interface OrganisationSubscriptionsControllerFindAllRequest {
    orgUuid: string;
}

export interface OrganisationSubscriptionsControllerUpdateSubscriptionRequest {
    uuid: string;
    orgUuid: string;
    saveOrganisationSubscriptionRecordDto: SaveOrganisationSubscriptionRecordDto;
}

/**
 * OrganisationsApi - interface
 * 
 * @export
 * @interface OrganisationsApiInterface
 */
export interface OrganisationsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerFindAllForUserRaw(): Promise<runtime.ApiResponse<Array<Organisation>>>;

    /**
     */
    organisationControllerFindAllForUser(): Promise<Array<Organisation>>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerFindOneRaw(requestParameters: OrganisationControllerFindOneRequest): Promise<runtime.ApiResponse<Organisation>>;

    /**
     */
    organisationControllerFindOne(requestParameters: OrganisationControllerFindOneRequest): Promise<Organisation>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerRemoveRaw(requestParameters: OrganisationControllerRemoveRequest): Promise<runtime.ApiResponse<Organisation>>;

    /**
     */
    organisationControllerRemove(requestParameters: OrganisationControllerRemoveRequest): Promise<Organisation>;

    /**
     * 
     * @param {string} uuid 
     * @param {UpdateOrganisationDto} updateOrganisationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerUpdateRaw(requestParameters: OrganisationControllerUpdateRequest): Promise<runtime.ApiResponse<Organisation>>;

    /**
     */
    organisationControllerUpdate(requestParameters: OrganisationControllerUpdateRequest): Promise<Organisation>;

    /**
     * 
     * @param {string} orgUuid 
     * @param {CreateUpdateMembershipDto} createUpdateMembershipDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationMembershipsControllerCreateOrUpdateRaw(requestParameters: OrganisationMembershipsControllerCreateOrUpdateRequest): Promise<runtime.ApiResponse<Organisation>>;

    /**
     */
    organisationMembershipsControllerCreateOrUpdate(requestParameters: OrganisationMembershipsControllerCreateOrUpdateRequest): Promise<Organisation>;

    /**
     * 
     * @param {string} orgUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationMembershipsControllerFindAllRaw(requestParameters: OrganisationMembershipsControllerFindAllRequest): Promise<runtime.ApiResponse<Array<Organisation>>>;

    /**
     */
    organisationMembershipsControllerFindAll(requestParameters: OrganisationMembershipsControllerFindAllRequest): Promise<Array<Organisation>>;

    /**
     * 
     * @param {string} orgUuid 
     * @param {string} membershipUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationMembershipsControllerRemoveRaw(requestParameters: OrganisationMembershipsControllerRemoveRequest): Promise<runtime.ApiResponse<boolean>>;

    /**
     */
    organisationMembershipsControllerRemove(requestParameters: OrganisationMembershipsControllerRemoveRequest): Promise<boolean>;

    /**
     * 
     * @param {string} orgUuid 
     * @param {SaveOrganisationSubscriptionRecordDto} saveOrganisationSubscriptionRecordDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationSubscriptionsControllerAddSubscriptionRaw(requestParameters: OrganisationSubscriptionsControllerAddSubscriptionRequest): Promise<runtime.ApiResponse<OrganisationSubscriptionRecord>>;

    /**
     */
    organisationSubscriptionsControllerAddSubscription(requestParameters: OrganisationSubscriptionsControllerAddSubscriptionRequest): Promise<OrganisationSubscriptionRecord>;

    /**
     * 
     * @param {string} orgUuid 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationSubscriptionsControllerDeleteSubscriptionRaw(requestParameters: OrganisationSubscriptionsControllerDeleteSubscriptionRequest): Promise<runtime.ApiResponse<boolean>>;

    /**
     */
    organisationSubscriptionsControllerDeleteSubscription(requestParameters: OrganisationSubscriptionsControllerDeleteSubscriptionRequest): Promise<boolean>;

    /**
     * 
     * @param {string} orgUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationSubscriptionsControllerFindAllRaw(requestParameters: OrganisationSubscriptionsControllerFindAllRequest): Promise<runtime.ApiResponse<Array<OrganisationSubscriptionRecord>>>;

    /**
     */
    organisationSubscriptionsControllerFindAll(requestParameters: OrganisationSubscriptionsControllerFindAllRequest): Promise<Array<OrganisationSubscriptionRecord>>;

    /**
     * 
     * @param {string} uuid 
     * @param {string} orgUuid 
     * @param {SaveOrganisationSubscriptionRecordDto} saveOrganisationSubscriptionRecordDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationSubscriptionsControllerUpdateSubscriptionRaw(requestParameters: OrganisationSubscriptionsControllerUpdateSubscriptionRequest): Promise<runtime.ApiResponse<OrganisationSubscriptionRecord>>;

    /**
     */
    organisationSubscriptionsControllerUpdateSubscription(requestParameters: OrganisationSubscriptionsControllerUpdateSubscriptionRequest): Promise<OrganisationSubscriptionRecord>;

}

/**
 * 
 */
export class OrganisationsApi extends runtime.BaseAPI implements OrganisationsApiInterface {

    /**
     */
    async organisationControllerFindAllForUserRaw(): Promise<runtime.ApiResponse<Array<Organisation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganisationFromJSON));
    }

    /**
     */
    async organisationControllerFindAllForUser(): Promise<Array<Organisation>> {
        const response = await this.organisationControllerFindAllForUserRaw();
        return await response.value();
    }

    /**
     */
    async organisationControllerFindOneRaw(requestParameters: OrganisationControllerFindOneRequest): Promise<runtime.ApiResponse<Organisation>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationControllerFindOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationFromJSON(jsonValue));
    }

    /**
     */
    async organisationControllerFindOne(requestParameters: OrganisationControllerFindOneRequest): Promise<Organisation> {
        const response = await this.organisationControllerFindOneRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationControllerRemoveRaw(requestParameters: OrganisationControllerRemoveRequest): Promise<runtime.ApiResponse<Organisation>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationFromJSON(jsonValue));
    }

    /**
     */
    async organisationControllerRemove(requestParameters: OrganisationControllerRemoveRequest): Promise<Organisation> {
        const response = await this.organisationControllerRemoveRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationControllerUpdateRaw(requestParameters: OrganisationControllerUpdateRequest): Promise<runtime.ApiResponse<Organisation>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationControllerUpdate.');
        }

        if (requestParameters.updateOrganisationDto === null || requestParameters.updateOrganisationDto === undefined) {
            throw new runtime.RequiredError('updateOrganisationDto','Required parameter requestParameters.updateOrganisationDto was null or undefined when calling organisationControllerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganisationDtoToJSON(requestParameters.updateOrganisationDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationFromJSON(jsonValue));
    }

    /**
     */
    async organisationControllerUpdate(requestParameters: OrganisationControllerUpdateRequest): Promise<Organisation> {
        const response = await this.organisationControllerUpdateRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationMembershipsControllerCreateOrUpdateRaw(requestParameters: OrganisationMembershipsControllerCreateOrUpdateRequest): Promise<runtime.ApiResponse<Organisation>> {
        if (requestParameters.orgUuid === null || requestParameters.orgUuid === undefined) {
            throw new runtime.RequiredError('orgUuid','Required parameter requestParameters.orgUuid was null or undefined when calling organisationMembershipsControllerCreateOrUpdate.');
        }

        if (requestParameters.createUpdateMembershipDto === null || requestParameters.createUpdateMembershipDto === undefined) {
            throw new runtime.RequiredError('createUpdateMembershipDto','Required parameter requestParameters.createUpdateMembershipDto was null or undefined when calling organisationMembershipsControllerCreateOrUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{orgUuid}/memberships`.replace(`{${"orgUuid"}}`, encodeURIComponent(String(requestParameters.orgUuid))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUpdateMembershipDtoToJSON(requestParameters.createUpdateMembershipDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationFromJSON(jsonValue));
    }

    /**
     */
    async organisationMembershipsControllerCreateOrUpdate(requestParameters: OrganisationMembershipsControllerCreateOrUpdateRequest): Promise<Organisation> {
        const response = await this.organisationMembershipsControllerCreateOrUpdateRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationMembershipsControllerFindAllRaw(requestParameters: OrganisationMembershipsControllerFindAllRequest): Promise<runtime.ApiResponse<Array<Organisation>>> {
        if (requestParameters.orgUuid === null || requestParameters.orgUuid === undefined) {
            throw new runtime.RequiredError('orgUuid','Required parameter requestParameters.orgUuid was null or undefined when calling organisationMembershipsControllerFindAll.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{orgUuid}/memberships`.replace(`{${"orgUuid"}}`, encodeURIComponent(String(requestParameters.orgUuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganisationFromJSON));
    }

    /**
     */
    async organisationMembershipsControllerFindAll(requestParameters: OrganisationMembershipsControllerFindAllRequest): Promise<Array<Organisation>> {
        const response = await this.organisationMembershipsControllerFindAllRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationMembershipsControllerRemoveRaw(requestParameters: OrganisationMembershipsControllerRemoveRequest): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.orgUuid === null || requestParameters.orgUuid === undefined) {
            throw new runtime.RequiredError('orgUuid','Required parameter requestParameters.orgUuid was null or undefined when calling organisationMembershipsControllerRemove.');
        }

        if (requestParameters.membershipUuid === null || requestParameters.membershipUuid === undefined) {
            throw new runtime.RequiredError('membershipUuid','Required parameter requestParameters.membershipUuid was null or undefined when calling organisationMembershipsControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{orgUuid}/memberships/{membershipUuid}`.replace(`{${"orgUuid"}}`, encodeURIComponent(String(requestParameters.orgUuid))).replace(`{${"membershipUuid"}}`, encodeURIComponent(String(requestParameters.membershipUuid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async organisationMembershipsControllerRemove(requestParameters: OrganisationMembershipsControllerRemoveRequest): Promise<boolean> {
        const response = await this.organisationMembershipsControllerRemoveRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationSubscriptionsControllerAddSubscriptionRaw(requestParameters: OrganisationSubscriptionsControllerAddSubscriptionRequest): Promise<runtime.ApiResponse<OrganisationSubscriptionRecord>> {
        if (requestParameters.orgUuid === null || requestParameters.orgUuid === undefined) {
            throw new runtime.RequiredError('orgUuid','Required parameter requestParameters.orgUuid was null or undefined when calling organisationSubscriptionsControllerAddSubscription.');
        }

        if (requestParameters.saveOrganisationSubscriptionRecordDto === null || requestParameters.saveOrganisationSubscriptionRecordDto === undefined) {
            throw new runtime.RequiredError('saveOrganisationSubscriptionRecordDto','Required parameter requestParameters.saveOrganisationSubscriptionRecordDto was null or undefined when calling organisationSubscriptionsControllerAddSubscription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{orgUuid}/subscriptions`.replace(`{${"orgUuid"}}`, encodeURIComponent(String(requestParameters.orgUuid))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveOrganisationSubscriptionRecordDtoToJSON(requestParameters.saveOrganisationSubscriptionRecordDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationSubscriptionRecordFromJSON(jsonValue));
    }

    /**
     */
    async organisationSubscriptionsControllerAddSubscription(requestParameters: OrganisationSubscriptionsControllerAddSubscriptionRequest): Promise<OrganisationSubscriptionRecord> {
        const response = await this.organisationSubscriptionsControllerAddSubscriptionRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationSubscriptionsControllerDeleteSubscriptionRaw(requestParameters: OrganisationSubscriptionsControllerDeleteSubscriptionRequest): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.orgUuid === null || requestParameters.orgUuid === undefined) {
            throw new runtime.RequiredError('orgUuid','Required parameter requestParameters.orgUuid was null or undefined when calling organisationSubscriptionsControllerDeleteSubscription.');
        }

        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationSubscriptionsControllerDeleteSubscription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{orgUuid}/subscriptions/{uuid}`.replace(`{${"orgUuid"}}`, encodeURIComponent(String(requestParameters.orgUuid))).replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async organisationSubscriptionsControllerDeleteSubscription(requestParameters: OrganisationSubscriptionsControllerDeleteSubscriptionRequest): Promise<boolean> {
        const response = await this.organisationSubscriptionsControllerDeleteSubscriptionRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationSubscriptionsControllerFindAllRaw(requestParameters: OrganisationSubscriptionsControllerFindAllRequest): Promise<runtime.ApiResponse<Array<OrganisationSubscriptionRecord>>> {
        if (requestParameters.orgUuid === null || requestParameters.orgUuid === undefined) {
            throw new runtime.RequiredError('orgUuid','Required parameter requestParameters.orgUuid was null or undefined when calling organisationSubscriptionsControllerFindAll.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{orgUuid}/subscriptions`.replace(`{${"orgUuid"}}`, encodeURIComponent(String(requestParameters.orgUuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganisationSubscriptionRecordFromJSON));
    }

    /**
     */
    async organisationSubscriptionsControllerFindAll(requestParameters: OrganisationSubscriptionsControllerFindAllRequest): Promise<Array<OrganisationSubscriptionRecord>> {
        const response = await this.organisationSubscriptionsControllerFindAllRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async organisationSubscriptionsControllerUpdateSubscriptionRaw(requestParameters: OrganisationSubscriptionsControllerUpdateSubscriptionRequest): Promise<runtime.ApiResponse<OrganisationSubscriptionRecord>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationSubscriptionsControllerUpdateSubscription.');
        }

        if (requestParameters.orgUuid === null || requestParameters.orgUuid === undefined) {
            throw new runtime.RequiredError('orgUuid','Required parameter requestParameters.orgUuid was null or undefined when calling organisationSubscriptionsControllerUpdateSubscription.');
        }

        if (requestParameters.saveOrganisationSubscriptionRecordDto === null || requestParameters.saveOrganisationSubscriptionRecordDto === undefined) {
            throw new runtime.RequiredError('saveOrganisationSubscriptionRecordDto','Required parameter requestParameters.saveOrganisationSubscriptionRecordDto was null or undefined when calling organisationSubscriptionsControllerUpdateSubscription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{orgUuid}/subscriptions/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))).replace(`{${"orgUuid"}}`, encodeURIComponent(String(requestParameters.orgUuid))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaveOrganisationSubscriptionRecordDtoToJSON(requestParameters.saveOrganisationSubscriptionRecordDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationSubscriptionRecordFromJSON(jsonValue));
    }

    /**
     */
    async organisationSubscriptionsControllerUpdateSubscription(requestParameters: OrganisationSubscriptionsControllerUpdateSubscriptionRequest): Promise<OrganisationSubscriptionRecord> {
        const response = await this.organisationSubscriptionsControllerUpdateSubscriptionRaw(requestParameters);
        return await response.value();
    }

}
