/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PaymentSessionReference,
    PaymentSessionReferenceFromJSON,
    PaymentSessionReferenceToJSON,
} from '../models';

/**
 * PaymentReferencesApi - interface
 * 
 * @export
 * @interface PaymentReferencesApiInterface
 */
export interface PaymentReferencesApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentReferencesApiInterface
     */
    paymentSessionReferenceControllerFindAllRaw(): Promise<runtime.ApiResponse<Array<PaymentSessionReference>>>;

    /**
     */
    paymentSessionReferenceControllerFindAll(): Promise<Array<PaymentSessionReference>>;

}

/**
 * 
 */
export class PaymentReferencesApi extends runtime.BaseAPI implements PaymentReferencesApiInterface {

    /**
     */
    async paymentSessionReferenceControllerFindAllRaw(): Promise<runtime.ApiResponse<Array<PaymentSessionReference>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/payment-reference`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PaymentSessionReferenceFromJSON));
    }

    /**
     */
    async paymentSessionReferenceControllerFindAll(): Promise<Array<PaymentSessionReference>> {
        const response = await this.paymentSessionReferenceControllerFindAllRaw();
        return await response.value();
    }

}
