/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BooleanResult,
    BooleanResultFromJSON,
    BooleanResultToJSON,
    PersonDto,
    PersonDtoFromJSON,
    PersonDtoToJSON,
} from '../models';

export interface PersonControllerFindOneRequest {
    uuid: string;
}

export interface PersonControllerRemoveRequest {
    uuid: string;
}

export interface PersonControllerUpdateRequest {
    uuid: string;
    body: object;
}

/**
 * PersonsApi - interface
 * 
 * @export
 * @interface PersonsApiInterface
 */
export interface PersonsApiInterface {
    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonsApiInterface
     */
    personControllerFindOneRaw(requestParameters: PersonControllerFindOneRequest): Promise<runtime.ApiResponse<PersonDto>>;

    /**
     */
    personControllerFindOne(requestParameters: PersonControllerFindOneRequest): Promise<PersonDto>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonsApiInterface
     */
    personControllerRemoveRaw(requestParameters: PersonControllerRemoveRequest): Promise<runtime.ApiResponse<BooleanResult>>;

    /**
     */
    personControllerRemove(requestParameters: PersonControllerRemoveRequest): Promise<BooleanResult>;

    /**
     * 
     * @param {string} uuid 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonsApiInterface
     */
    personControllerUpdateRaw(requestParameters: PersonControllerUpdateRequest): Promise<runtime.ApiResponse<BooleanResult>>;

    /**
     */
    personControllerUpdate(requestParameters: PersonControllerUpdateRequest): Promise<BooleanResult>;

}

/**
 * 
 */
export class PersonsApi extends runtime.BaseAPI implements PersonsApiInterface {

    /**
     */
    async personControllerFindOneRaw(requestParameters: PersonControllerFindOneRequest): Promise<runtime.ApiResponse<PersonDto>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling personControllerFindOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/person/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonDtoFromJSON(jsonValue));
    }

    /**
     */
    async personControllerFindOne(requestParameters: PersonControllerFindOneRequest): Promise<PersonDto> {
        const response = await this.personControllerFindOneRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async personControllerRemoveRaw(requestParameters: PersonControllerRemoveRequest): Promise<runtime.ApiResponse<BooleanResult>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling personControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/person/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BooleanResultFromJSON(jsonValue));
    }

    /**
     */
    async personControllerRemove(requestParameters: PersonControllerRemoveRequest): Promise<BooleanResult> {
        const response = await this.personControllerRemoveRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async personControllerUpdateRaw(requestParameters: PersonControllerUpdateRequest): Promise<runtime.ApiResponse<BooleanResult>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling personControllerUpdate.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling personControllerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/person/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BooleanResultFromJSON(jsonValue));
    }

    /**
     */
    async personControllerUpdate(requestParameters: PersonControllerUpdateRequest): Promise<BooleanResult> {
        const response = await this.personControllerUpdateRaw(requestParameters);
        return await response.value();
    }

}
