/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InitUserResponseDto,
    InitUserResponseDtoFromJSON,
    InitUserResponseDtoToJSON,
} from '../models';

/**
 * UsersApi - interface
 * 
 * @export
 * @interface UsersApiInterface
 */
export interface UsersApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    userOnboardingControllerInitUserRaw(): Promise<runtime.ApiResponse<InitUserResponseDto>>;

    /**
     */
    userOnboardingControllerInitUser(): Promise<InitUserResponseDto>;

}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI implements UsersApiInterface {

    /**
     */
    async userOnboardingControllerInitUserRaw(): Promise<runtime.ApiResponse<InitUserResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user-onboarding/init-user`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InitUserResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async userOnboardingControllerInitUser(): Promise<InitUserResponseDto> {
        const response = await this.userOnboardingControllerInitUserRaw();
        return await response.value();
    }

}
