packages:
    - apps/*
    - libs/*

injectWorkspacePackages: true

allowBuilds:
    "@nestjs/core": true
    "@scarf/scarf": true
    "@swc/core": true
    core-js: true
    esbuild: true
    msgpackr-extract: true
    nestjs-pino: true
    nx: true
    protobufjs: true
    sharp: true
    unrs-resolver: true
    vscode-material-icon-theme-js: true
