import { Container } from "../components/Container.jsx";
import Layout from "../components/Layout.jsx";

export default function Home() {
    const url = process.env.NEXT_PUBLIC_APP_BASE_PATH;
    const email = "info@usemiller.dev";
    return (
        <Layout
            seoDescription="Miller dev tools save you time so you can focus on building your product and helping your customers."
            seoTitle={`Dev tools to save you time`}
            headerTitle="Miller Dev Tools"
            themeColor="violet"
        >
            <Container>
                <article className="prose prose-lg prose-invert mx-auto">
                    <h1>Privacy Policy</h1>
                    <h2>1. Introduction</h2>
                    <p>
                        This Privacy Policy applies to the website {url}{" "}
                        (hereinafter the “website”) published by Darragh
                        ORiordan (hereinafter “Miller” or “we”) and its other
                        services and products for which personal data is being
                        communicated to Miller.
                    </p>
                    <p>
                        Please read this Privacy Policy carefully as it explains
                        how Miller uses your personal data and how to exercise
                        your rights. This Privacy Policy supplements the Terms &
                        Conditions or any documents or notices that may refer to
                        this Privacy Policy.
                    </p>
                    <p>
                        Should you have any questions, you may directly contact
                        Miller by sending an email to {email}.
                    </p>
                    <h2>2. Definitions</h2>
                    <p>
                        DATA means data about a living individual who can be
                        identified from those data (or from those and other
                        information either in our possession or likely to come
                        into our possession).
                    </p>
                    <p>
                        USAGE DATA is data collected automatically either
                        generated by the use of Service or from Service
                        infrastructure itself (for example, the duration of a
                        page visit).
                    </p>
                    <p>
                        COOKIES are small files stored on your device (computer
                        or mobile device).
                    </p>
                    <p>
                        DATA CONTROLLER means a natural or legal person who
                        (either alone or jointly or in common with other
                        persons) determines the purposes for which and the
                        manner in which any personal data are, or are to be,
                        processed. For the purpose of this Privacy Policy, we
                        are a Data Controller of your data.
                    </p>
                    <p>
                        DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural
                        or legal person who processes the data on behalf of the
                        Data Controller. We may use the services of various
                        Service Providers in order to process your data more
                        effectively.
                    </p>
                    <p>
                        DATA SUBJECT is any living individual who is the subject
                        of Personal Data.
                    </p>
                    <p>
                        THE USER is the individual using our Service. The User
                        corresponds to the Data Subject, who is the subject of
                        Personal Data.
                    </p>
                    <h2>3. Legal context</h2>
                    <p>
                        We abide by the recommendations of the relevant
                        authorities and have put in place an organization to
                        ensure our compliance with the regulatory framework
                        established by the General Data Protection Regulation
                        (EU) 2016/679 of the European Parliament and of the
                        Council (GDPR) and any other laws or regulations
                        relating to personal information that apply to us.
                    </p>
                    <h2>4. What is our role?</h2>
                    <p>
                        Under the GDPR, we are considered as a data controller.
                        It means that we set the whys and hows we process your
                        personal information. For example, when you are visiting
                        our website, we are in charge of determining the
                        purposes and the means that are necessary to administer,
                        operate and manage our users' personal information that
                        we collect from it.
                    </p>
                    <p>
                        Depending on the activity we perform on your data, we
                        may also be considered as a data processor. This means
                        that you are our customer's end user and that we are
                        processing your data under the instructions of our
                        customer considered as a data controller. In this case,
                        the data controller sets the purposes and means of the
                        processing activity, and we abide and deliver our
                        service in regards to these.
                    </p>
                    <h2>5. What kind of personal information do we process?</h2>
                    <p>
                        We only collect and process personal information that is
                        relevant and adequate. We give special attention to its
                        accuracy and updates when needed. Personal information
                        includes in particular:
                    </p>
                    <p>
                        Connection data e.g. IP address, logs, terminal and
                        connection identifiers, timestamp, etc.
                    </p>
                    <p>
                        Internet data e.g. cookies, tracers, navigation data,
                        audience metrics, etc.
                    </p>
                    <p>
                        The collection of this information may at times be
                        mandatory in order to provide our service, other times
                        optional to enhance your experience and left to your
                        good will. Mandatory information will be identified as
                        such when we collect your data. Know that if you refuse
                        to provide it, Miller won't be able to provide you with
                        its utmost service and you will unfortunately experience
                        inconveniences.
                    </p>
                    <h2>6. When do we collect your personal information?</h2>
                    <p>
                        We collect your personal information on various
                        occasions.
                    </p>
                    <p>
                        Primarily on a Website or software visit when an
                        Individual browsed our website or our solution
                    </p>
                    <h2>7. How do we use your personal information?</h2>
                    <p>
                        Your personal information will never be processed for
                        incompatible purposes regarding why it was first
                        collected. We only collect and process personal
                        information for specified, explicit and legitimate
                        purposes, like:
                    </p>
                    <p>- Website audience measurement</p>
                    <p>- To gather analytics on the website traffic</p>
                    <p>
                        In order to comply with the principle of lawfulness, the
                        legal bases for each data processing is determined
                        carefully and on a case-by-case basis in accordance with
                        the list provided by Article 6 of the GDPR.
                    </p>
                    <p>
                        We do not process your data or use automated decision
                        making without your knowledge, nor do we sell or rent
                        your personal information without your explicit consent.
                    </p>
                    <h2>8. Who can access your personal information?</h2>
                    <p>
                        Recipients to whom we disclose your personal information
                        are carefully chosen by us. They receive data for
                        legitimate purposes, especially when it comes to
                        pursuing our business activity and providing a
                        qualitative service:
                    </p>

                    <p>Plausible.io for analytics</p>
                    <p>
                        Certain data recipients are considered our data
                        processors in accordance with Article 28 of the GDPR,
                        which means we review how they handle personal
                        information and make sure they put in place appropriate
                        guarantees to protect it.
                    </p>
                    <p>
                        Other recipients are considered authorized third parties
                        in accordance with Article 4 of the GDPR, which means we
                        have to communicate your personal information to them to
                        comply with applicable legal obligations, lawful
                        requests and processes (subpoenas, requests from
                        government or tax authorities, etc.).
                    </p>
                    <h2>9. Where do we transfer your personal information?</h2>
                    <p>
                        As far as possible, your personal information is
                        processed within the European Union. However, some of
                        our service providers may be located in another country
                        of which you are a resident or pursuing their activity
                        outside of the European Union.
                    </p>
                    <p>
                        When we transfer your personal information to a
                        recipient outside the European Union, we take care of
                        putting in place sufficient guarantees in accordance
                        with the list provided by Articles 44 to 50 of the GDPR,
                        whether it is having it stored in a country with an
                        adequate privacy protection or contracting Data
                        Protection Agreements to ensure your personal
                        information is protected.
                    </p>
                    <p>Plausible.io in Europe</p>
                    <h2>10. How long do we store your personal information?</h2>
                    <p>
                        As a general rule when we are considered a data
                        controller by the GDPR, retention periods of your
                        personal information are determined according to the
                        purposes for which we collected it and our legal
                        obligations.
                    </p>
                    <p>
                        Regarding our activities as a data processor, we retain
                        our customers' end users personal information as long as
                        required by our terms and conditions and the pursuing of
                        the service our customers' subscribed to.
                    </p>
                    <p>
                        When these purposes are fulfilled or when you ask us,
                        your personal information is archived, erased or
                        anonymized.
                    </p>
                    <h2>11. How do we protect your personal information?</h2>
                    <p>
                        We care deeply about the safety of your personal
                        information and that is why we put in place adequate
                        technical and organizational security measures to
                        preserve its confidentiality, integrity and
                        availability.
                    </p>
                    <p>
                        We take into account the risks for your rights and
                        freedoms and therefore follow with great care the
                        recommendations of the competent authorities regarding
                        security.
                    </p>
                    <h2>12. What are your rights and how to exercise them?</h2>
                    <p>
                        In accordance with Articles 12 to 23 of GDPR, you have
                        rights over your personal information that we are
                        committed to respect:
                    </p>
                    <ul>
                        <li>
                            you can request access to your personal information
                            and a copy of it
                        </li>
                        <li>
                            you can ask us to modify your personal information
                            if you consider it obsolete, inaccurate or
                            incomplete.
                        </li>
                        <li>
                            you can object to the processing of your personal
                            information if based on our legitimate interest in
                            certain circumstances.
                        </li>

                        <li>
                            you can request to restrict the processing during a
                            limited period of time, in certain circumstances.
                        </li>
                        <li>
                            you can opt-out from a consent already given,
                            without this withdrawal affecting the lawfulness of
                            the processing operations already carried out.
                        </li>
                        <li>
                            when technically feasible, you can ask us to send
                            you the personal information you provided us or that
                            we communicate it to a third party.
                        </li>
                        <li>
                            you can ask us to delete your personal information
                            if it meets legal grounds for which it is
                            applicable.
                        </li>
                    </ul>
                    <p>
                        These rights can be exercised directly and at any time
                        by sending an email to {url} or on our Data Requests
                        page. In the case you are our customer's end user,
                        please take into consideration that this request will be
                        forwarded and must be answered directly by them.
                    </p>
                    <h2>13. Children's privacy</h2>
                    <p>
                        Our Services are not intended for use by children under
                        the age of 13 (" Children").
                    </p>
                    <p>
                        We do not knowingly collect personally identifiable
                        information from Children under 13. If you become aware
                        that a Child has provided us with Personal Data, please
                        contact us. If we become aware that we have collected
                        Personal Data from Children without verification of
                        parental consent, we take steps to remove that
                        information from our servers.
                    </p>
                    <h2>14. Policy changes</h2>
                    <p>
                        This Privacy Policy may be modified in the future to
                        keep it updated with legal jurisprudence and evolution.
                        You'll be informed either by a special mention on this
                        page or by a personalized warning, by email for
                        instance.
                    </p>
                    <h2>15. Contact us</h2>
                    <p>
                        If you have any questions about this Privacy Policy,
                        please contact us via email at {email}
                    </p>
                    <h2>Cookie Policy</h2>
                    <p>
                        Part of the provision of our service and this website
                        relies on the collection of cookies. Depending on their
                        use, they may be considered essential or subject to your
                        explicit consent.
                    </p>
                    <h3>What is a cookie?</h3>
                    <p>
                        A cookie is a small text file that may be deposited and
                        saved on the hard drive of your device (computer,
                        tablet, smartphone, etc.) when you visit our website. It
                        allows us or third parties to identify the device on
                        which it has been saved and to keep record of certain
                        information relating to your journey in order, for
                        instance, to simplify your visit on our website, to
                        secure your connection or to adapt the content of a page
                        to your interests.
                    </p>
                    <h3>What types of cookies are collected?</h3>
                    <p>Analytics and Performance Cookies</p>
                    <p>
                        These cookies are useful to measure the audience and
                        performance of our website and help us understand how
                        visitors interact with it.
                    </p>
                    <h3>How to manage cookies?</h3>
                    <p>
                        Your internet browser may allow you to manage your
                        cookie preferences by removing or rejecting them via
                        your browser settings (usually located in "help",
                        “tools” or “edit” sections). Remember that if you choose
                        to disable our cookies, you may experience some
                        inconvenience when using our website.
                    </p>
                </article>
            </Container>
        </Layout>
    );
}
