receivers:
    otlp:
        protocols:
            grpc:
            http:

exporters:
    prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
            label1: value1

    logging:

    otlp:
        endpoint: jaeger-all-in-one:4317
        tls:
            insecure: true
processors:
    batch:

extensions:
    health_check:
    pprof:
        endpoint: :1888
    zpages:
        endpoint: :55679

service:
    telemetry:
        logs:
            level: "debug" # default is info
    extensions: [pprof, zpages, health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp, logging, prometheus]
