/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInvitationDto
 */
export interface CreateInvitationDto {
    /**
     * 
     * @type {string}
     * @memberof CreateInvitationDto
     */
    givenName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvitationDto
     */
    emailAddress: string;
    /**
     * 
     * @type {number}
     * @memberof CreateInvitationDto
     */
    organisationId: number;
}

export function CreateInvitationDtoFromJSON(json: any): CreateInvitationDto {
    return CreateInvitationDtoFromJSONTyped(json, false);
}

export function CreateInvitationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInvitationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'givenName': json['givenName'],
        'emailAddress': json['emailAddress'],
        'organisationId': json['organisationId'],
    };
}

export function CreateInvitationDtoToJSON(value?: CreateInvitationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'givenName': value.givenName,
        'emailAddress': value.emailAddress,
        'organisationId': value.organisationId,
    };
}


