/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUpdateMembershipDto
 */
export interface CreateUpdateMembershipDto {
    /**
     * 
     * @type {number}
     * @memberof CreateUpdateMembershipDto
     */
    personId: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateUpdateMembershipDto
     */
    roles: Array<string>;
}

export function CreateUpdateMembershipDtoFromJSON(json: any): CreateUpdateMembershipDto {
    return CreateUpdateMembershipDtoFromJSONTyped(json, false);
}

export function CreateUpdateMembershipDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUpdateMembershipDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'personId': json['personId'],
        'roles': json['roles'],
    };
}

export function CreateUpdateMembershipDtoToJSON(value?: CreateUpdateMembershipDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'personId': value.personId,
        'roles': value.roles,
    };
}


