/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileMetaDto
 */
export interface FileMetaDto {
    /**
     * 
     * @type {string}
     * @memberof FileMetaDto
     */
    contents: string;
    /**
     * 
     * @type {string}
     * @memberof FileMetaDto
     */
    fileLocation: string;
    /**
     * 
     * @type {string}
     * @memberof FileMetaDto
     */
    nearestReadmeLocation?: string;
}

export function FileMetaDtoFromJSON(json: any): FileMetaDto {
    return FileMetaDtoFromJSONTyped(json, false);
}

export function FileMetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMetaDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': json['contents'],
        'fileLocation': json['fileLocation'],
        'nearestReadmeLocation': !exists(json, 'nearestReadmeLocation') ? undefined : json['nearestReadmeLocation'],
    };
}

export function FileMetaDtoToJSON(value?: FileMetaDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': value.contents,
        'fileLocation': value.fileLocation,
        'nearestReadmeLocation': value.nearestReadmeLocation,
    };
}


