/* tslint:disable */
/* eslint-disable */
/**
 * Miller App BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InitUserDto
 */
export interface InitUserDto {
    /**
     *
     * @type {boolean}
     * @memberof InitUserDto
     */
    userWasInitialised: boolean;
}

export function InitUserDtoFromJSON(json: any): InitUserDto {
    return InitUserDtoFromJSONTyped(json, false);
}

export function InitUserDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): InitUserDto {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        userWasInitialised: json["userWasInitialised"],
    };
}

export function InitUserDtoToJSON(value?: InitUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        userWasInitialised: value.userWasInitialised,
    };
}
