/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MembershipRole
 */
export interface MembershipRole {
    /**
     * 
     * @type {number}
     * @memberof MembershipRole
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof MembershipRole
     */
    membershipId: number;
    /**
     * 
     * @type {string}
     * @memberof MembershipRole
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof MembershipRole
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof MembershipRole
     */
    updateDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof MembershipRole
     */
    deletedDate: Date;
}

export function MembershipRoleFromJSON(json: any): MembershipRole {
    return MembershipRoleFromJSONTyped(json, false);
}

export function MembershipRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'membershipId': json['membershipId'],
        'name': json['name'],
        'createdDate': (new Date(json['createdDate'])),
        'updateDate': (new Date(json['updateDate'])),
        'deletedDate': (new Date(json['deletedDate'])),
    };
}

export function MembershipRoleToJSON(value?: MembershipRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'membershipId': value.membershipId,
        'name': value.name,
        'createdDate': (value.createdDate.toISOString()),
        'updateDate': (value.updateDate.toISOString()),
        'deletedDate': (value.deletedDate.toISOString()),
    };
}


