/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationSubscriptionRecord
 */
export interface OrganisationSubscriptionRecord {
    /**
     * 
     * @type {number}
     * @memberof OrganisationSubscriptionRecord
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    productDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    paymentSystemTransactionId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    paymentSystemProductId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    paymentSystemCustomerId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    paymentSystemCustomerEmail: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    paymentSystemMode: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    paymentSystemName: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganisationSubscriptionRecord
     */
    validUntil: Date;
    /**
     * 
     * @type {number}
     * @memberof OrganisationSubscriptionRecord
     */
    organisationId: number;
    /**
     * 
     * @type {Date}
     * @memberof OrganisationSubscriptionRecord
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganisationSubscriptionRecord
     */
    updatedDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganisationSubscriptionRecord
     */
    deletedDate: Date;
}

export function OrganisationSubscriptionRecordFromJSON(json: any): OrganisationSubscriptionRecord {
    return OrganisationSubscriptionRecordFromJSONTyped(json, false);
}

export function OrganisationSubscriptionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationSubscriptionRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'productDisplayName': json['productDisplayName'],
        'paymentSystemTransactionId': json['paymentSystemTransactionId'],
        'paymentSystemProductId': json['paymentSystemProductId'],
        'paymentSystemCustomerId': json['paymentSystemCustomerId'],
        'paymentSystemCustomerEmail': json['paymentSystemCustomerEmail'],
        'paymentSystemMode': json['paymentSystemMode'],
        'paymentSystemName': json['paymentSystemName'],
        'validUntil': (new Date(json['validUntil'])),
        'organisationId': json['organisationId'],
        'createdDate': (new Date(json['createdDate'])),
        'updatedDate': (new Date(json['updatedDate'])),
        'deletedDate': (new Date(json['deletedDate'])),
    };
}

export function OrganisationSubscriptionRecordToJSON(value?: OrganisationSubscriptionRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'productDisplayName': value.productDisplayName,
        'paymentSystemTransactionId': value.paymentSystemTransactionId,
        'paymentSystemProductId': value.paymentSystemProductId,
        'paymentSystemCustomerId': value.paymentSystemCustomerId,
        'paymentSystemCustomerEmail': value.paymentSystemCustomerEmail,
        'paymentSystemMode': value.paymentSystemMode,
        'paymentSystemName': value.paymentSystemName,
        'validUntil': (value.validUntil.toISOString()),
        'organisationId': value.organisationId,
        'createdDate': (value.createdDate.toISOString()),
        'updatedDate': (value.updatedDate.toISOString()),
        'deletedDate': (value.deletedDate.toISOString()),
    };
}


