/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationSubscriptionRecord
 */
export interface OrganisationSubscriptionRecord {
    /**
     * 
     * @type {number}
     * @memberof OrganisationSubscriptionRecord
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    stripeSubscriptionId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    stripeCustomerId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSubscriptionRecord
     */
    stripePriceId: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganisationSubscriptionRecord
     */
    validUntil: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganisationSubscriptionRecord
     */
    createdDate: Date;
}

export function OrganisationSubscriptionRecordFromJSON(json: any): OrganisationSubscriptionRecord {
    return OrganisationSubscriptionRecordFromJSONTyped(json, false);
}

export function OrganisationSubscriptionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationSubscriptionRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'stripeSubscriptionId': json['stripeSubscriptionId'],
        'stripeCustomerId': json['stripeCustomerId'],
        'stripePriceId': json['stripePriceId'],
        'validUntil': (new Date(json['validUntil'])),
        'createdDate': (new Date(json['createdDate'])),
    };
}

export function OrganisationSubscriptionRecordToJSON(value?: OrganisationSubscriptionRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'stripeSubscriptionId': value.stripeSubscriptionId,
        'stripeCustomerId': value.stripeCustomerId,
        'stripePriceId': value.stripePriceId,
        'validUntil': (value.validUntil.toISOString()),
        'createdDate': (value.createdDate.toISOString()),
    };
}


