/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgGithubUser
 */
export interface OrgGithubUser {
    /**
     * 
     * @type {number}
     * @memberof OrgGithubUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof OrgGithubUser
     */
    orgUuid: string;
    /**
     * 
     * @type {string}
     * @memberof OrgGithubUser
     */
    ghUsername: string;
    /**
     * 
     * @type {Date}
     * @memberof OrgGithubUser
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrgGithubUser
     */
    updateDate: Date;
}

export function OrgGithubUserFromJSON(json: any): OrgGithubUser {
    return OrgGithubUserFromJSONTyped(json, false);
}

export function OrgGithubUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgGithubUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgUuid': json['orgUuid'],
        'ghUsername': json['ghUsername'],
        'createdDate': (new Date(json['createdDate'])),
        'updateDate': (new Date(json['updateDate'])),
    };
}

export function OrgGithubUserToJSON(value?: OrgGithubUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'orgUuid': value.orgUuid,
        'ghUsername': value.ghUsername,
        'createdDate': (value.createdDate.toISOString()),
        'updateDate': (value.updateDate.toISOString()),
    };
}


