/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentSessionReference
 */
export interface PaymentSessionReference {
    /**
     * 
     * @type {number}
     * @memberof PaymentSessionReference
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentSessionReference
     */
    uuid: string;
    /**
     * 
     * @type {Date}
     * @memberof PaymentSessionReference
     */
    createdDate: Date;
}

export function PaymentSessionReferenceFromJSON(json: any): PaymentSessionReference {
    return PaymentSessionReferenceFromJSONTyped(json, false);
}

export function PaymentSessionReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentSessionReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'createdDate': (new Date(json['createdDate'])),
    };
}

export function PaymentSessionReferenceToJSON(value?: PaymentSessionReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'createdDate': (value.createdDate.toISOString()),
    };
}


