/* tslint:disable */
/* eslint-disable */
/**
 * Miller App BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    uuid: string;
    /**
     * 
     * @type {boolean}
     * @memberof Person
     */
    emailVerified: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Person
     */
    blocked: boolean;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    picture: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    auth0UserId: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    username?: string;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    updateDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    deletedDate: Date;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'uuid': json['uuid'],
        'emailVerified': json['emailVerified'],
        'blocked': json['blocked'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'familyName': !exists(json, 'familyName') ? undefined : json['familyName'],
        'givenName': !exists(json, 'givenName') ? undefined : json['givenName'],
        'picture': json['picture'],
        'auth0UserId': json['auth0UserId'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'createdDate': (new Date(json['createdDate'])),
        'updateDate': (new Date(json['updateDate'])),
        'deletedDate': (new Date(json['deletedDate'])),
    };
}

export function PersonToJSON(value?: Person | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'uuid': value.uuid,
        'emailVerified': value.emailVerified,
        'blocked': value.blocked,
        'name': value.name,
        'familyName': value.familyName,
        'givenName': value.givenName,
        'picture': value.picture,
        'auth0UserId': value.auth0UserId,
        'username': value.username,
        'createdDate': (value.createdDate.toISOString()),
        'updateDate': (value.updateDate.toISOString()),
        'deletedDate': (value.deletedDate.toISOString()),
    };
}


