/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueItemDto
 */
export interface QueueItemDto {
    /**
     * 
     * @type {string}
     * @memberof QueueItemDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof QueueItemDto
     */
    queueDateLocal: Date;
    /**
     * 
     * @type {string}
     * @memberof QueueItemDto
     */
    result: string;
    /**
     * 
     * @type {string}
     * @memberof QueueItemDto
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof QueueItemDto
     */
    failReason?: string;
}

export function QueueItemDtoFromJSON(json: any): QueueItemDto {
    return QueueItemDtoFromJSONTyped(json, false);
}

export function QueueItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'queueDateLocal': (new Date(json['queueDateLocal'])),
        'result': json['result'],
        'data': json['data'],
        'failReason': !exists(json, 'failReason') ? undefined : json['failReason'],
    };
}

export function QueueItemDtoToJSON(value?: QueueItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'queueDateLocal': (value.queueDateLocal.toISOString()),
        'result': value.result,
        'data': value.data,
        'failReason': value.failReason,
    };
}


