/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveOrganisationSubscriptionRecordDto
 */
export interface SaveOrganisationSubscriptionRecordDto {
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    productDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    paymentSystemTransactionId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    paymentSystemProductId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    millerPaymentReferenceUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    paymentSystemCustomerId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    paymentSystemMode: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    paymentSystemName: string;
    /**
     * 
     * @type {Date}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    validUntil: Date;
}

export function SaveOrganisationSubscriptionRecordDtoFromJSON(json: any): SaveOrganisationSubscriptionRecordDto {
    return SaveOrganisationSubscriptionRecordDtoFromJSONTyped(json, false);
}

export function SaveOrganisationSubscriptionRecordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveOrganisationSubscriptionRecordDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productDisplayName': json['productDisplayName'],
        'paymentSystemTransactionId': json['paymentSystemTransactionId'],
        'paymentSystemProductId': json['paymentSystemProductId'],
        'millerPaymentReferenceUuid': !exists(json, 'millerPaymentReferenceUuid') ? undefined : json['millerPaymentReferenceUuid'],
        'paymentSystemCustomerId': json['paymentSystemCustomerId'],
        'paymentSystemMode': json['paymentSystemMode'],
        'paymentSystemName': json['paymentSystemName'],
        'validUntil': (new Date(json['validUntil'])),
    };
}

export function SaveOrganisationSubscriptionRecordDtoToJSON(value?: SaveOrganisationSubscriptionRecordDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productDisplayName': value.productDisplayName,
        'paymentSystemTransactionId': value.paymentSystemTransactionId,
        'paymentSystemProductId': value.paymentSystemProductId,
        'millerPaymentReferenceUuid': value.millerPaymentReferenceUuid,
        'paymentSystemCustomerId': value.paymentSystemCustomerId,
        'paymentSystemMode': value.paymentSystemMode,
        'paymentSystemName': value.paymentSystemName,
        'validUntil': (value.validUntil.toISOString()),
    };
}


