/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveSubscriptionAssetDto
 */
export interface SaveSubscriptionAssetDto {
    /**
     * 
     * @type {number}
     * @memberof SaveSubscriptionAssetDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SaveSubscriptionAssetDto
     */
    internalSku: string;
    /**
     * 
     * @type {string}
     * @memberof SaveSubscriptionAssetDto
     */
    uri: string;
    /**
     * 
     * @type {string}
     * @memberof SaveSubscriptionAssetDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof SaveSubscriptionAssetDto
     */
    displayName: string;
}

export function SaveSubscriptionAssetDtoFromJSON(json: any): SaveSubscriptionAssetDto {
    return SaveSubscriptionAssetDtoFromJSONTyped(json, false);
}

export function SaveSubscriptionAssetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveSubscriptionAssetDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'internalSku': json['internalSku'],
        'uri': json['uri'],
        'description': json['description'],
        'displayName': json['displayName'],
    };
}

export function SaveSubscriptionAssetDtoToJSON(value?: SaveSubscriptionAssetDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'internalSku': value.internalSku,
        'uri': value.uri,
        'description': value.description,
        'displayName': value.displayName,
    };
}


