/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveOrganisationSubscriptionRecordDto
 */
export interface SaveOrganisationSubscriptionRecordDto {
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    stripeSubscriptionId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    stripeCustomerId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    stripePriceId: string;
    /**
     * 
     * @type {Date}
     * @memberof SaveOrganisationSubscriptionRecordDto
     */
    validUntil: Date;
}

export function SaveOrganisationSubscriptionRecordDtoFromJSON(json: any): SaveOrganisationSubscriptionRecordDto {
    return SaveOrganisationSubscriptionRecordDtoFromJSONTyped(json, false);
}

export function SaveOrganisationSubscriptionRecordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveOrganisationSubscriptionRecordDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stripeSubscriptionId': json['stripeSubscriptionId'],
        'stripeCustomerId': json['stripeCustomerId'],
        'stripePriceId': json['stripePriceId'],
        'validUntil': (new Date(json['validUntil'])),
    };
}

export function SaveOrganisationSubscriptionRecordDtoToJSON(value?: SaveOrganisationSubscriptionRecordDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stripeSubscriptionId': value.stripeSubscriptionId,
        'stripeCustomerId': value.stripeCustomerId,
        'stripePriceId': value.stripePriceId,
        'validUntil': (value.validUntil.toISOString()),
    };
}


