/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeCheckoutSessionResponseDto
 */
export interface StripeCheckoutSessionResponseDto {
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutSessionResponseDto
     */
    stripeSessionId: string;
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutSessionResponseDto
     */
    stripeSessionUrl: string;
}

export function StripeCheckoutSessionResponseDtoFromJSON(json: any): StripeCheckoutSessionResponseDto {
    return StripeCheckoutSessionResponseDtoFromJSONTyped(json, false);
}

export function StripeCheckoutSessionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCheckoutSessionResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stripeSessionId': json['stripeSessionId'],
        'stripeSessionUrl': json['stripeSessionUrl'],
    };
}

export function StripeCheckoutSessionResponseDtoToJSON(value?: StripeCheckoutSessionResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stripeSessionId': value.stripeSessionId,
        'stripeSessionUrl': value.stripeSessionUrl,
    };
}


