/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeCheckoutLineItem
 */
export interface StripeCheckoutLineItem {
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutLineItem
     */
    price: string;
    /**
     * 
     * @type {number}
     * @memberof StripeCheckoutLineItem
     */
    quantity: number;
}

export function StripeCheckoutLineItemFromJSON(json: any): StripeCheckoutLineItem {
    return StripeCheckoutLineItemFromJSONTyped(json, false);
}

export function StripeCheckoutLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCheckoutLineItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'price': json['price'],
        'quantity': json['quantity'],
    };
}

export function StripeCheckoutLineItemToJSON(value?: StripeCheckoutLineItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price': value.price,
        'quantity': value.quantity,
    };
}


