/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeCheckoutEvent
 */
export interface StripeCheckoutEvent {
    /**
     * 
     * @type {number}
     * @memberof StripeCheckoutEvent
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof StripeCheckoutEvent
     */
    createdDate: Date;
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutEvent
     */
    clientReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutEvent
     */
    stripeSessionId: string;
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutEvent
     */
    stripeObjectType: string;
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutEvent
     */
    stripeDataAsString: string;
}

export function StripeCheckoutEventFromJSON(json: any): StripeCheckoutEvent {
    return StripeCheckoutEventFromJSONTyped(json, false);
}

export function StripeCheckoutEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCheckoutEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdDate': (new Date(json['createdDate'])),
        'clientReferenceId': !exists(json, 'clientReferenceId') ? undefined : json['clientReferenceId'],
        'stripeSessionId': json['stripeSessionId'],
        'stripeObjectType': json['stripeObjectType'],
        'stripeDataAsString': json['stripeDataAsString'],
    };
}

export function StripeCheckoutEventToJSON(value?: StripeCheckoutEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdDate': (value.createdDate.toISOString()),
        'clientReferenceId': value.clientReferenceId,
        'stripeSessionId': value.stripeSessionId,
        'stripeObjectType': value.stripeObjectType,
        'stripeDataAsString': value.stripeDataAsString,
    };
}


