/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeCustomerPortalRequestDto
 */
export interface StripeCustomerPortalRequestDto {
    /**
     * 
     * @type {string}
     * @memberof StripeCustomerPortalRequestDto
     */
    subscriptionRecordUuid: string;
    /**
     * 
     * @type {string}
     * @memberof StripeCustomerPortalRequestDto
     */
    returnUrl: string;
}

export function StripeCustomerPortalRequestDtoFromJSON(json: any): StripeCustomerPortalRequestDto {
    return StripeCustomerPortalRequestDtoFromJSONTyped(json, false);
}

export function StripeCustomerPortalRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCustomerPortalRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subscriptionRecordUuid': json['subscriptionRecordUuid'],
        'returnUrl': json['returnUrl'],
    };
}

export function StripeCustomerPortalRequestDtoToJSON(value?: StripeCustomerPortalRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subscriptionRecordUuid': value.subscriptionRecordUuid,
        'returnUrl': value.returnUrl,
    };
}


