/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateOrganisationDto
 */
export interface UpdateOrganisationDto {
    /**
     * 
     * @type {Array<User>}
     * @memberof UpdateOrganisationDto
     */
    members?: Array<User>;
    /**
     * 
     * @type {User}
     * @memberof UpdateOrganisationDto
     */
    owner?: User;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganisationDto
     */
    name?: string;
}

export function UpdateOrganisationDtoFromJSON(json: any): UpdateOrganisationDto {
    return UpdateOrganisationDtoFromJSONTyped(json, false);
}

export function UpdateOrganisationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganisationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'members': !exists(json, 'members') ? undefined : ((json['members'] as Array<any>).map(UserFromJSON)),
        'owner': !exists(json, 'owner') ? undefined : UserFromJSON(json['owner']),
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UpdateOrganisationDtoToJSON(value?: UpdateOrganisationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'members': value.members === undefined ? undefined : ((value.members as Array<any>).map(UserToJSON)),
        'owner': UserToJSON(value.owner),
        'name': value.name,
    };
}


