/* tslint:disable */
/* eslint-disable */
/**
 * Use Miller BE
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserApiKey
 */
export interface UserApiKey {
    /**
     * 
     * @type {number}
     * @memberof UserApiKey
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserApiKey
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof UserApiKey
     */
    apiKey: string;
    /**
     * 
     * @type {string}
     * @memberof UserApiKey
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof UserApiKey
     */
    userId: number;
    /**
     * 
     * @type {Date}
     * @memberof UserApiKey
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserApiKey
     */
    updateDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserApiKey
     */
    deletedDate: Date;
}

export function UserApiKeyFromJSON(json: any): UserApiKey {
    return UserApiKeyFromJSONTyped(json, false);
}

export function UserApiKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'apiKey': json['apiKey'],
        'description': json['description'],
        'userId': json['userId'],
        'createdDate': (new Date(json['createdDate'])),
        'updateDate': (new Date(json['updateDate'])),
        'deletedDate': (new Date(json['deletedDate'])),
    };
}

export function UserApiKeyToJSON(value?: UserApiKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'apiKey': value.apiKey,
        'description': value.description,
        'userId': value.userId,
        'createdDate': (value.createdDate.toISOString()),
        'updateDate': (value.updateDate.toISOString()),
        'deletedDate': (value.deletedDate.toISOString()),
    };
}


